service: pareto${self:provider.implementation}

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: Stg
  implementation: Content
  environment:
    DYNAMODB_TABLE: Content-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: scripts/create.create
    customName: DataInsertDynamodb
    name: ${self:service}${self:functions.create.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80 
    role: arn:aws:iam::240968882250:role/LambdaExecutionRole
   
    events:
      - http:
          path: Content/{id}
          method: post
          cors: true

  list:
    handler: scripts/list.list
    customName: DataListDynamodb
    name: ${self:service}${self:functions.list.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80
    role: arn:aws:iam::240968882250:role/LambdaExecutionRole
   
    events:
      - http:
          path: Content
          method: get
          cors: true

  get:
    handler: scripts/get.get
    customName: DataListByIdDynamodb
    name: ${self:service}${self:functions.get.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80
    role: arn:aws:iam::240968882250:role/LambdaExecutionRole
    package:
     #include: (comment exclude if you want to include node modules)
      exclude:
        - node_modules/**
    events:
      - http:
          path: Content/{id}
          method: get
          cors: true

  update:
    handler: scripts/update.update
    customName: DataUpdateDynamodb
    name: ${self:service}${self:functions.update.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80
    role: arn:aws:iam::240968882250:role/LambdaExecutionRole
    
    events:
      - http:
          path: Content/{id}
          method: put
          cors: true

  delete:
    handler: scripts/delete.delete
    customName: DataDeleteDynamodb
    name: ${self:service}${self:functions.delete.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80
    role: arn:aws:iam::240968882250:role/LambdaExecutionRole
    
    events:
      - http:
          path: Content/{id}
          method: delete
          cors: true

  search:
    handler: scripts/search.search
    customName: DataSearchDynamodb
    name: ${self:service}${self:functions.search.customName}Function-${self:provider.stage}
    description: This lambda is a subscriber a subscriber for api gate way 
    memorySize: 128 
    timeout: 80 
    environment:
      AWS_TableName_HashKey: Id     
    events:
      - http:
          path: Search/Content
          method: post
          cors: true


resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}API-${self:provider.stage}
        Description: This is an search api to expose content table data based on search parameters
    # DynamoDbTable:
      # Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      # Properties:
        # AttributeDefinitions:
          # -
            # AttributeName: Id
            # AttributeType: S
        # KeySchema:
          # -
            # AttributeName: Id
            # KeyType: HASH
        # ProvisionedThroughput:
          # ReadCapacityUnits: 5
          # WriteCapacityUnits: 5
        # TableName: ${self:provider.environment.DYNAMODB_TABLE}
